[versions]
micronaut-application = "4.6.2"
shadow = "8.3.9"
quartz = "2.3.2"
pac4j = "6.0.4"
smbj = "0.13.0"
poi = "5.2.5"
opencsv = "5.9"

[libraries]
quartz = { module = "org.quartz-scheduler:quartz", version.ref = "quartz" }
pac4j-saml = { module = "org.pac4j:pac4j-saml", version.ref = "pac4j" }
pac4j-core = { module = "org.pac4j:pac4j-core", version.ref = "pac4j" }
smbj = { module = "com.hierynomus:smbj", version.ref = "smbj" }
reactor-core = { module = "io.projectreactor:reactor-core" }

micronaut-http-validation = { module = "io.micronaut:micronaut-http-validation" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor" }
micronaut-data-processor = { module = "io.micronaut.data:micronaut-data-processor" }
micronaut-security-annotations = { module = "io.micronaut.security:micronaut-security-annotations" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson" }
micronaut-data-jdbc = { module = "io.micronaut.data:micronaut-data-jdbc" }
micronaut-jdbc-hikari = { module = "io.micronaut.sql:micronaut-jdbc-hikari" }
micronaut-cache-caffeine = { module = "io.micronaut.cache:micronaut-cache-caffeine" }
micronaut-security = { module = "io.micronaut.security:micronaut-security" }
micronaut-security-jwt = { module = "io.micronaut.security:micronaut-security-jwt" }
micronaut-security-oauth2 = { module = "io.micronaut.security:micronaut-security-oauth2" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }

logback-classic = { module = "ch.qos.logback:logback-classic" }
postgresql = { module = "org.postgresql:postgresql" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
micronaut-liquibase = { module = "io.micronaut.liquibase:micronaut-liquibase" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-application" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronaut-application" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
