import winrm
import argparse
import textwrap
import datetime
import random
import os

GROUPS = ["IT", "HR", "FIN", "CS", "RMC"]
BASE_NAMES = ["James", "Mary", "Robert", "Patricia", "John", "Jennifer", "Michael", "Linda", "David", "Elizabeth", "William", "Barbara", "Richard", "Susan", "Joseph", "Jessica", "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Nancy", "Daniel", "Lisa", "Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra", "Donald", "Ashley", "Steven", "Kimberly", "Paul", "Emily", "Andrew", "Donna", "Joshua", "Michelle", "Kenneth", "Dorothy", "Kevin", "Carol", "Brian", "Amanda", "George", "Melissa", "Edward", "Deborah", "Azman"]

def generate_users():
    """Pre-generate users in Python to ensure consistency with generated SQL."""
    users = []
    # Generate 10 users per group
    for group in GROUPS:
        for i in range(1, 11):
            base_name = random.choice(BASE_NAMES)
            if i == 1 and group == "IT":
                base_name = "Azman"
            
            username = f"{group}_{base_name}"
            # Unique suffix to avoid duplicates in seeding
            username = f"{username}_{random.randint(100, 999)}"
            users.append({"username": username, "group": group})
    return users

def generate_user_sql(users):
    """Generate SQL file for inserting users into user_account and user_role tables."""
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"create_{ts}_users.sql"
    password = "Password123!"
    
    with open(filename, "w") as f:
        f.write("-- SQL to seed users generated by seed_ad_smb.py\n")
        f.write(f"-- Generated at: {datetime.datetime.now().isoformat()}\n\n")
        
        for user in users:
            uname = user['username']
            # Using ON CONFLICT (username) DO NOTHING to avoid errors on re-run
            f.write(f"INSERT INTO user_account (username, password) VALUES ('{uname}', '{password}') ON CONFLICT (username) DO NOTHING;\n")
            # Link to the 'USER' role
            f.write(f"INSERT INTO user_role (user_id, role_id) SELECT id, (SELECT id FROM role WHERE name = 'USER') FROM user_account WHERE username = '{uname}' AND NOT EXISTS (SELECT 1 FROM user_role ur JOIN role r ON ur.role_id = r.id WHERE ur.user_id = user_account.id AND r.name = 'USER');\n\n")
            
    return filename

def generate_powershell_script(domain, pregenerated_users, root_path="C:\\Shared", total_count=10000, with_exception=False, delete_only=False):
    exception_rate = 50 if with_exception else 0
    
    # Convert users to a PowerShell array of hash tables
    ps_users = "@(" + ", ".join([f"@{{uname='{u['username']}'; group='{u['group']}'}}" for u in pregenerated_users]) + ")"
    
    seeding_logic = ""
    if not delete_only:
        seeding_logic = textwrap.dedent(f"""
        Write-Host "Creating Active Directory Groups..."
        foreach ($GroupName in $Groups) {{
            if (-not (Get-ADGroup -Filter "Name -eq '$GroupName'" -ErrorAction SilentlyContinue)) {{
                New-ADGroup -Name $GroupName -GroupCategory Security -GroupScope Global
                Write-Host "Created group: $GroupName"
            }}
        }}

        Write-Host "Creating Users and adding to groups..."
        $CreatedUsers = @()
        $UsersToCreate = {ps_users}
        
        foreach ($UserDef in $UsersToCreate) {{
            $FinalUsername = $UserDef.uname
            $Group = $UserDef.group
            
            try {{
                $Password = ConvertTo-SecureString "Password123!" -AsPlainText -Force
                if (-not (Get-ADUser -Filter "SamAccountName -eq '$FinalUsername'" -ErrorAction SilentlyContinue)) {{
                    New-ADUser -Name $FinalUsername -SamAccountName $FinalUsername -UserPrincipalName "$FinalUsername@{domain}.local" -AccountPassword $Password -Enabled $true
                    Add-ADGroupMember -Identity $Group -Members $FinalUsername
                    Write-Host "Created user $FinalUsername and added to $Group"
                }}
                $CreatedUsers += $FinalUsername
            }} catch {{
                Write-Host "Failed to create user $FinalUsername: $_"
            }}
        }}

        if (-not (Test-Path $SharedRoot)) {{
            New-Item -ItemType Directory -Path $SharedRoot | Out-Null
            # Share the root folder
            $ShareName = (Split-Path $SharedRoot -Leaf) -or "Shared"
            if (-not (Get-SmbShare -Name $ShareName -ErrorAction SilentlyContinue)) {{
                New-SmbShare -Name $ShareName -Path $SharedRoot -FullAccess "Everyone"
            }}
        }}

        Write-Host "Creating Department Folders..."
        foreach ($Group in $Groups) {{
            $FolderPath = Join-Path $SharedRoot $Group
            if (-not (Test-Path $FolderPath)) {{
                New-Item -ItemType Directory -Path $FolderPath | Out-Null
            }}
        }}

        Write-Host "Generating files and folders..."
        $totalEntities = {total_count}
        $ActiveFolders = @()
        foreach ($Group in $Groups) {{ $ActiveFolders += Join-Path $SharedRoot $Group }}

        $FileExtensions = @(".txt", ".docx", ".xlsx", ".pdf", ".csv", ".log", ".dat", ".png", ".jpg", ".md")
        $Adjectives = @("Annual", "Quarterly", "Confidential", "Public", "Internal", "Draft", "Final", "Revised", "Archived", "Active", "Pending", "Approved", "Strategic", "Operational", "Global", "Regional", "Local", "Backup", "Secret", "Official")
        $Nouns = @("Report", "Strategy", "Budget", "Forecast", "Analysis", "Summary", "Proposal", "Plan", "Review", "Audit", "Meeting", "Minutes", "Agenda", "Schedule", "Memo", "Policy", "Procedure", "Manual", "Contract", "Presentation")
        
        $random = New-Object System.Random

        # Directories
        $targetFolderCount = [math]::Round($totalEntities * 0.1)
        for ($i = 0; $i -lt $targetFolderCount; $i++) {{
            $ParentFolder = $ActiveFolders[$random.Next(0, $ActiveFolders.Count)]
            $NewFolderName = "$($Adjectives[$random.Next(0, $Adjectives.Count)])_$($Nouns[$random.Next(0, $Nouns.Count)])_$($random.Next(1000, 9999))"
            $NewFolderPath = Join-Path $ParentFolder $NewFolderName
            if ($NewFolderPath.Length -lt 220 -and -not (Test-Path $NewFolderPath)) {{
                New-Item -ItemType Directory -Path $NewFolderPath | Out-Null
                $ActiveFolders += $NewFolderPath
            }}
        }}

        # Files
        $targetFileCount = $totalEntities - $targetFolderCount
        for ($i = 0; $i -lt $targetFileCount; $i++) {{
            $TargetFolder = $ActiveFolders[$random.Next(0, $ActiveFolders.Count)]
            $FileName = "$($Adjectives[$random.Next(0, $Adjectives.Count)])_$($Nouns[$random.Next(0, $Nouns.Count)])_$($random.Next(1000, 9999))$($FileExtensions[$random.Next(0, $FileExtensions.Count)])"
            $FilePath = Join-Path $TargetFolder $FileName
            [io.file]::WriteAllText($FilePath, "Seed data created at $(Get-Date)")
            if ($i % 1000 -eq 0) {{ Write-Host "Prog: $([math]::Round(($i/$targetFileCount)*100))%" }}
        }}

        Write-Host "Applying permissions..."
        $AllItems = Get-ChildItem -Path $SharedRoot -Recurse -Force
        foreach ($Item in $AllItems) {{
            try {{
                $Dept = "IT"
                foreach ($g in $Groups) {{ if ($Item.FullName -like "*\\$g\\*") {{ $Dept = $g; break }} }}
                $Acl = Get-Acl $Item.FullName
                
                if ($random.Next(0, 100) -lt 5) {{
                    $TargetIdentity = "Builtin\\Administrators"
                    $OwnerIdentity = New-Object System.Security.Principal.NTAccount("Builtin", "Administrators")
                }} else {{
                    $DeptUsers = $CreatedUsers | Where-Object {{ $_ -match "^$Dept" }}
                    $TargetUsr = if ($null -ne $DeptUsers -and $random.Next(0, 100) -ge 30) {{ 
                        if ($DeptUsers -is [array]) {{ $DeptUsers[$random.Next(0, $DeptUsers.Count)] }} else {{ $DeptUsers }}
                    }} else {{ $CreatedUsers[$random.Next(0, $CreatedUsers.Count)] }}
                    $TargetIdentity = "{domain}\\$TargetUsr"
                    $OwnerIdentity = New-Object System.Security.Principal.NTAccount("{domain}", $TargetUsr)
                }}
                
                $Acl.SetOwner($OwnerIdentity)
                if ($random.Next(0, 100) -lt {exception_rate}) {{
                    $Acl.SetAccessRuleProtection($true, $false)
                    $ExplicitRules = $Acl.GetAccessRules($true, $false, [System.Security.Principal.NTAccount])
                    foreach($rule in $ExplicitRules) {{ $Acl.RemoveAccessRule($rule) | Out-Null }}
                }}
                $Rule = New-Object System.Security.AccessControl.FileSystemAccessRule($TargetIdentity, "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
                $Acl.AddAccessRule($Rule)
                Set-Acl -Path $Item.FullName -AclObject $Acl
            }} catch {{ }}
        }}
        """)

    return textwrap.dedent(f"""
    $ErrorActionPreference = "Stop"
    $Groups = @("IT", "HR", "FIN", "CS", "RMC")

    # Privilege elevation logic
    $def = @'
    using System;
    using System.Runtime.InteropServices;
    public class TokenPriv {{
        [DllImport("advapi32.dll", ExactSpelling = true, SetLastError = true)]
        public static extern bool OpenProcessToken(IntPtr h, int acc, ref IntPtr tkp);
        [DllImport("advapi32.dll", SetLastError = true)]
        public static extern bool LookupPrivilegeValue(string host, string name, ref long luid);
        [DllImport("advapi32.dll", SetLastError = true)]
        public static extern bool AdjustTokenPrivileges(IntPtr tk, bool dis, ref TP newst, int len, IntPtr prev, IntPtr relen);
        [StructLayout(LayoutKind.Sequential)]
        public struct TP {{ public int Count; public long Luid; public int Attr; }}
    }}
'@
    Add-Type -TypeDefinition $def -ErrorAction SilentlyContinue
    $process = [System.Diagnostics.Process]::GetCurrentProcess().Handle
    $tkp = [IntPtr]::Zero
    [TokenPriv]::OpenProcessToken($process, 0x28, [ref]$tkp) | Out-Null
    $luid = 0L
    [TokenPriv]::LookupPrivilegeValue($null, "SeRestorePrivilege", [ref]$luid) | Out-Null
    $tp = New-Object TokenPriv+TP; $tp.Count = 1; $tp.Luid = $luid; $tp.Attr = 0x2
    [TokenPriv]::AdjustTokenPrivileges($tkp, $false, [ref]$tp, 0, [IntPtr]::Zero, [IntPtr]::Zero) | Out-Null
    [TokenPriv]::LookupPrivilegeValue($null, "SeTakeOwnershipPrivilege", [ref]$luid) | Out-Null
    $tp.Luid = $luid
    [TokenPriv]::AdjustTokenPrivileges($tkp, $false, [ref]$tp, 0, [IntPtr]::Zero, [IntPtr]::Zero) | Out-Null

    $SharedRoot = "{root_path}"
    if (Test-Path $SharedRoot) {{
        Write-Host "Cleaning up $SharedRoot..."
        & takeown.exe /F $SharedRoot /R /D Y | Out-Null
        & icacls.exe $SharedRoot /reset /T /C /L /Q | Out-Null
        Get-ChildItem -Path $SharedRoot -Force | Remove-Item -Recurse -Force
    }}
    
    {seeding_logic}
    """)

def main():
    parser = argparse.ArgumentParser(description="Seed Windows Server with AD Users and custom SMB structure.")
    parser.add_argument("--host", required=True)
    parser.add_argument("--domain", default="DEV")
    parser.add_argument("--path", required=True)
    parser.add_argument("--user", required=True)
    parser.add_argument("--password", required=True)
    parser.add_argument("--transport", default="ntlm", choices=["ntlm", "kerberos", "basic", "credssp"])
    parser.add_argument("--cert-validation", default="ignore", choices=["ignore", "validate"])
    
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--create", type=int, help="Seed both AD and Files/Folders.")
    group.add_argument("--delete", action="store_true")

    parser.add_argument("--exception", action="store_true")
    args = parser.parse_args()

    try:
        session = winrm.Session(
            args.host,
            auth=(args.user, args.password),
            transport=args.transport,
            server_cert_validation=('ignore' if args.cert_validation == 'ignore' else 'validate')
        )
        
        pregenerated_users = []
        if args.create is not None:
            print("Generating User seeding SQL (Application side)...")
            pregenerated_users = generate_users()
            sql_file = generate_user_sql(pregenerated_users)
            print(f"Created: {sql_file}")
        
        ps_script = generate_powershell_script(
            args.domain, pregenerated_users, root_path=args.path,
            total_count=args.create if args.create is not None else 10000, 
            with_exception=args.exception, delete_only=args.delete
        )
        
        print("Uploading and executing remote PowerShell payload...")
        import base64
        b64_script = base64.b64encode(ps_script.encode('utf-8')).decode('utf-8')
        session.run_cmd(r'powershell -Command "if (Test-Path C:\Windows\Temp\seed.b64) { Remove-Item C:\Windows\Temp\seed.b64 -Force }"')
        for i in range(0, len(b64_script), 2000):
            chunk = b64_script[i:i+2000]
            session.run_cmd(f'cmd.exe /c echo {chunk}>> C:\\Windows\\Temp\\seed.b64')
            
        decoder_ps = r"""
        $b64 = Get-Content C:\Windows\Temp\seed.b64 -Raw
        $b64 = $b64 -replace "`r", "" -replace "`n", "" -replace " ", ""
        $bytes = [System.Convert]::FromBase64String($b64)
        $script = [System.Text.Encoding]::UTF8.GetString($bytes)
        $script | Out-File C:\Windows\Temp\seed.ps1 -Encoding UTF8 -Force
        & C:\Windows\Temp\seed.ps1
        """
        result = session.run_ps(decoder_ps)
        if result.status_code == 0:
            print("[SUCCESS] PowerShell seeding complete.")
            if result.std_out: print(result.std_out.decode('utf-8'))
        else:
            print(f"[ERROR] PsCode {result.status_code}")
            if result.std_out: print(result.std_out.decode('utf-8'))
            if result.std_err: print(result.std_err.decode('utf-8'))

    except Exception as e:
        print(f"[CRITICAL ERROR] {e}")

if __name__ == "__main__":
    main()
