package backend.util;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Properties;
import java.util.UUID;

public class SecretGenerator {
  
  public static void ensureSecrets() {
    File configDir = new File("config");
    if (!configDir.exists()) configDir.mkdirs();
    
    File secretsFile = new File("config/secrets.properties");
    if (!secretsFile.exists()) {
      Properties props = new Properties();
      // Generate a secure random-looking string
      String secret = UUID.randomUUID().toString() + UUID.randomUUID().toString();
      props.setProperty("micronaut.security.token.jwt.signatures.secret", secret);
      
      try (FileOutputStream out = new FileOutputStream(secretsFile)) {
        props.store(out, "Autogenerated Secrets - DO NOT COMMIT TO GIT");
        System.out.println("Generated new secret file at " + secretsFile.getAbsolutePath());
      } catch (Exception e) {
        System.err.println("Failed to generate secrets file: " + e.getMessage());
      }
    }
    
    // Load secrets into system properties so Micronaut picked them up
    if (secretsFile.exists()) {
      try (FileInputStream in = new FileInputStream(secretsFile)) {
        Properties props = new Properties();
        props.load(in);
        props.forEach((k, v) -> System.setProperty(k.toString(), v.toString()));
      } catch (Exception e) {
        System.err.println("Failed to load secrets file: " + e.getMessage());
      }
    }
  }
}
